(function(){
  const storageKey='emtel_theme';
  function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem(storageKey,theme);const button=document.getElementById('themeToggle');if(button){button.innerHTML=theme==='dark'?'<span class="theme-icon">☀️</span><span>Modo claro</span>':'<span class="theme-icon">🌙</span><span>Modo escuro</span>';button.setAttribute('aria-pressed',theme==='dark'?'true':'false')}}
  window.toggleEmtelTheme=function(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')};
  let cachedStats={pct:0,valid:0,total:0},lastStatsAt=0;
  function validationStats(force){if(!force&&Date.now()-lastStatsAt<15000)return cachedStats;try{const st=computeStats(MAIN_SHEET),pct=st.total?Math.round(st.val*100/st.total):0;cachedStats={pct,valid:st.val,total:st.total};lastStatsAt=Date.now()}catch(e){}return cachedStats}
  function updateControls(forceStats){const clock=document.getElementById('brasiliaClock'),date=document.getElementById('brasiliaDate'),value=document.getElementById('globalValidationValue'),fill=document.getElementById('globalValidationFill'),progress=document.getElementById('globalValidation');const now=new Date(),timeText=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now),dateText=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric'}).format(now),stats=validationStats(!!forceStats);if(clock)clock.textContent=timeText;if(date)date.textContent=dateText;if(value)value.textContent=stats.pct+'%';if(fill)fill.style.width=stats.pct+'%';if(progress){progress.title=stats.valid.toLocaleString('pt-BR')+' de '+stats.total.toLocaleString('pt-BR')+' cadastros validados';progress.setAttribute('aria-label','Progresso da validação: '+stats.pct+'%')}}
  function installControls(){const header=document.querySelector('header');if(!header||document.getElementById('globalControls'))return;const old=header.querySelector('.header-meta');if(old)old.remove();const controls=document.createElement('div');controls.id='globalControls';controls.className='global-controls';controls.innerHTML='<div class="global-control global-clock" title="Horário oficial de Brasília"><span>🇧🇷</span><div><strong id="brasiliaClock">--:--:--</strong><div id="brasiliaDate" style="font-size:9px;opacity:.78">--/--/----</div></div></div><div class="global-control global-progress" id="globalValidation"><span>✓</span><div class="global-progress-info"><div><strong id="globalValidationValue">0%</strong> validado</div><div class="global-progress-track"><div class="global-progress-fill" id="globalValidationFill"></div></div></div></div><button class="global-control" id="themeToggle" type="button" onclick="toggleEmtelTheme()" aria-label="Alternar modo de cor"></button>';header.appendChild(controls);updateControls()}
  const saved=localStorage.getItem(storageKey),preferred=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';applyTheme(saved||preferred);installControls();setInterval(updateControls,1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateControls()});
  const originalRenderForControls=window.render;window.render=function(){const result=originalRenderForControls.apply(this,arguments);installControls();updateControls(true);return result};
})();
